version: "3"
services:
    app:
        image: backend
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        env_file:
          - .env
        command: sh -c "alembic upgrade head"

        depends_on:
          - db
          - redis
        restart: on-failure

    db:
      image: "postgres:latest"
      restart: always
      ports:
        - "5435:5432"
      env_file:
        - .env
      volumes:
        - ./tmp/postgres_data:/var/lib/postgresql/data

    redis:
      image: "redis:latest"
      restart: always
      command: redis-server
      ports:
        - "6378:6379"
      volumes:
        - ./tmp/redis_data:/var/lib/redis/data

    celery:
      image: backend
      command: celery -A car_parser.celeryconfig worker --loglevel=info

      env_file:
        - .env
      volumes:
        - ./:/app
      depends_on:
        - app
        - db
        - redis
      restart: on-failure

    celery-beat:
      image: backend
      command: celery -A car_parser.celeryconfig beat --loglevel=info

      env_file:
        - .env
      volumes:
        - ./:/app
      depends_on:
        - app
        - db
        - redis
      restart: on-failure
